import type { Hotel } from "@/types/hotel";

export interface MockHotel extends Hotel {
  /** Base nightly price in KRW, before the date-based mock fluctuation. */
  basePrice: number;
}

function images(seed: string, count: number): string[] {
  return Array.from(
    { length: count },
    (_, i) => `https://picsum.photos/seed/${seed}-${i}/800/600`,
  );
}

export const mockHotels: MockHotel[] = [
  {
    id: "seoul-hanok-stay",
    name: "북촌 한옥 스테이",
    location: { city: "서울", country: "대한민국", address: "종로구 계동길 12" },
    aliases: ["seoul", "bukchon"],
    rating: 4.8,
    reviewCount: 612,
    images: images("seoul-hanok-stay", 4),
    amenities: ["무료 와이파이", "조식 포함", "공항 셔틀"],
    description:
      "북촌 한옥마을 한가운데 위치한 전통 한옥 숙소로, 고즈넉한 분위기와 현대적인 편의시설을 함께 제공합니다.",
    basePrice: 182000,
  },
  {
    id: "seoul-myeongdong-tower",
    name: "명동 타워 호텔",
    location: { city: "서울", country: "대한민국", address: "중구 명동길 26" },
    aliases: ["seoul", "myeongdong"],
    rating: 4.5,
    reviewCount: 1284,
    images: images("seoul-myeongdong-tower", 4),
    amenities: ["무료 와이파이", "피트니스 센터", "루프탑 바"],
    description: "명동 쇼핑가 중심부, 남산타워 전망을 갖춘 비즈니스 호텔입니다.",
    basePrice: 145000,
  },
  {
    id: "seoul-gangnam-suite",
    name: "강남 스위트 레지던스",
    location: { city: "서울", country: "대한민국", address: "강남구 테헤란로 152" },
    aliases: ["seoul", "gangnam"],
    rating: 4.6,
    reviewCount: 843,
    images: images("seoul-gangnam-suite", 4),
    amenities: ["무료 와이파이", "주방시설", "세탁시설"],
    description: "장기 출장객을 위한 풀옵션 레지던스형 객실을 제공하는 강남 중심 호텔입니다.",
    basePrice: 210000,
  },
  {
    id: "seoul-hongdae-pod",
    name: "홍대 포드 호텔",
    location: { city: "서울", country: "대한민국", address: "마포구 홍익로 8" },
    aliases: ["seoul", "hongdae"],
    rating: 4.2,
    reviewCount: 2031,
    images: images("seoul-hongdae-pod", 4),
    amenities: ["무료 와이파이", "24시간 프런트"],
    description: "홍대 클럽거리 도보 5분, 합리적인 가격의 캡슐형 디자인 호텔입니다.",
    basePrice: 88000,
  },
  {
    id: "tokyo-shinjuku-view",
    name: "신주쿠 뷰 호텔",
    location: { city: "도쿄", country: "일본", address: "신주쿠구 니시신주쿠 3-2" },
    aliases: ["tokyo", "shinjuku"],
    rating: 4.7,
    reviewCount: 1590,
    images: images("tokyo-shinjuku-view", 4),
    amenities: ["무료 와이파이", "온천", "조식 포함"],
    description: "신주쿠 마천루 전망과 대욕장을 갖춘 도심형 호텔입니다.",
    basePrice: 168000,
  },
  {
    id: "tokyo-asakusa-inn",
    name: "아사쿠사 전통 여관",
    location: { city: "도쿄", country: "일본", address: "다이토구 아사쿠사 1-15" },
    aliases: ["tokyo", "asakusa"],
    rating: 4.6,
    reviewCount: 731,
    images: images("tokyo-asakusa-inn", 4),
    amenities: ["다다미 객실", "유카타 제공", "조식 포함"],
    description: "센소지 도보 3분, 전통 다다미 객실에서 일본식 환대를 경험할 수 있습니다.",
    basePrice: 132000,
  },
  {
    id: "tokyo-shibuya-cross",
    name: "시부야 크로스 호텔",
    location: { city: "도쿄", country: "일본", address: "시부야구 도겐자카 1-1" },
    aliases: ["tokyo", "shibuya"],
    rating: 4.4,
    reviewCount: 2210,
    images: images("tokyo-shibuya-cross", 4),
    amenities: ["무료 와이파이", "피트니스 센터"],
    description: "시부야 스크램블 교차로 바로 앞에 위치한 모던 시티 호텔입니다.",
    basePrice: 155000,
  },
  {
    id: "tokyo-ginza-grand",
    name: "긴자 그랜드 호텔",
    location: { city: "도쿄", country: "일본", address: "긴자 5-8-1" },
    aliases: ["tokyo", "ginza"],
    rating: 4.9,
    reviewCount: 964,
    images: images("tokyo-ginza-grand", 4),
    amenities: ["무료 와이파이", "스파", "미쉐린 레스토랑"],
    description: "긴자 명품거리 한복판의 럭셔리 호텔로 최상급 서비스를 제공합니다.",
    basePrice: 298000,
  },
  {
    id: "osaka-dotonbori-central",
    name: "도톤보리 센트럴 호텔",
    location: { city: "오사카", country: "일본", address: "주오구 도톤보리 1-6" },
    aliases: ["osaka", "dotonbori"],
    rating: 4.5,
    reviewCount: 1876,
    images: images("osaka-dotonbori-central", 4),
    amenities: ["무료 와이파이", "24시간 프런트", "코인 세탁실"],
    description: "도톤보리 강변 번화가 한가운데, 관광과 쇼핑에 최적화된 위치입니다.",
    basePrice: 121000,
  },
  {
    id: "osaka-namba-park",
    name: "난바 파크 스테이",
    location: { city: "오사카", country: "일본", address: "나니와구 난바나카 2-10" },
    aliases: ["osaka", "namba"],
    rating: 4.3,
    reviewCount: 998,
    images: images("osaka-namba-park", 4),
    amenities: ["무료 와이파이", "조식 포함"],
    description: "난바역 도보 4분, 오사카 조 관광에도 편리한 가성비 호텔입니다.",
    basePrice: 96000,
  },
  {
    id: "osaka-umeda-sky",
    name: "우메다 스카이 호텔",
    location: { city: "오사카", country: "일본", address: "기타구 오요도나카 1-1" },
    aliases: ["osaka", "umeda"],
    rating: 4.7,
    reviewCount: 1342,
    images: images("osaka-umeda-sky", 4),
    amenities: ["무료 와이파이", "스카이라운지", "피트니스 센터"],
    description: "오사카역 인근 초고층 호텔로 도시 전경을 한눈에 담을 수 있습니다.",
    basePrice: 175000,
  },
  {
    id: "osaka-shinsekai-retro",
    name: "신세카이 레트로 인",
    location: { city: "오사카", country: "일본", address: "나니와구 에비스히가시 3-4" },
    aliases: ["osaka", "shinsekai"],
    rating: 4.1,
    reviewCount: 540,
    images: images("osaka-shinsekai-retro", 4),
    amenities: ["무료 와이파이", "대욕장"],
    description: "쓰텐카쿠 인근 레트로한 감성의 소규모 부티크 호텔입니다.",
    basePrice: 79000,
  },
  {
    id: "bangkok-sukhumvit-suite",
    name: "수쿰빗 스위트 호텔",
    location: { city: "방콕", country: "태국", address: "수쿰빗 소이 11" },
    aliases: ["bangkok", "sukhumvit"],
    rating: 4.6,
    reviewCount: 1765,
    images: images("bangkok-sukhumvit-suite", 4),
    amenities: ["루프탑 풀", "무료 와이파이", "조식 포함"],
    description: "수쿰빗 나이트라이프와 BTS 역이 가까운 인기 지역의 스위트 호텔입니다.",
    basePrice: 92000,
  },
  {
    id: "bangkok-riverside-resort",
    name: "리버사이드 리조트 방콕",
    location: { city: "방콕", country: "태국", address: "짜오프라야 강변로 88" },
    aliases: ["bangkok", "riverside", "chao phraya"],
    rating: 4.8,
    reviewCount: 2410,
    images: images("bangkok-riverside-resort", 4),
    amenities: ["강변 풀", "무료 셔틀보트", "스파"],
    description: "짜오프라야 강변에 위치한 리조트형 호텔로 셔틀보트로 왓아룬까지 이동이 편리합니다.",
    basePrice: 138000,
  },
  {
    id: "bangkok-siam-central",
    name: "시암 센트럴 호텔",
    location: { city: "방콕", country: "태국", address: "시암 스퀘어 소이 3" },
    aliases: ["bangkok", "siam"],
    rating: 4.4,
    reviewCount: 1102,
    images: images("bangkok-siam-central", 4),
    amenities: ["무료 와이파이", "쇼핑몰 직결"],
    description: "방콕 최대 쇼핑 상권인 시암 스퀘어와 바로 연결되는 도심형 호텔입니다.",
    basePrice: 76000,
  },
  {
    id: "bangkok-silom-budget",
    name: "실롬 버짓 인",
    location: { city: "방콕", country: "태국", address: "실롬 로드 45" },
    aliases: ["bangkok", "silom"],
    rating: 4.0,
    reviewCount: 655,
    images: images("bangkok-silom-budget", 4),
    amenities: ["무료 와이파이", "24시간 프런트"],
    description: "실롬 비즈니스 지구에 위치한 실속형 숙소로 BTS 역과 가깝습니다.",
    basePrice: 48000,
  },
];
